name: Main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruby-lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_APP_CONFIG: .bundle
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rubocop

  ruby-test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_APP_CONFIG: .bundle
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle config list
      - run: bundle exec rspec

  integration-tests:
    runs-on: ubuntu-latest
    env:
      BUNDLE_APP_CONFIG: .bundle
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: bundle exec yarn test
      - run: yarn lint

  release:
    runs-on: ubuntu-latest
    needs: [ruby-lint, ruby-test, integration-tests]
    if: github.ref == 'refs/heads/main'
    env:
      BUNDLE_APP_CONFIG: .bundle
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: npx semantic-release
        env:
          BUNDLE_FROZEN: false
